# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_created_by'),
        ('games', 'default_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesoffered',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamesoffered',
            name='linked_by',
        ),
        migrations.RemoveField(
            model_name='gamesoffered',
            name='location',
        ),
        migrations.AddField(
            model_name='game',
            name='locations',
            field=models.ManyToManyField(to='locations.Location'),
        ),
        migrations.DeleteModel(
            name='GamesOffered',
        ),
    ]
