# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokersessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokersession',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
