# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokersessions', '0002_pokersession_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokersessioncomment',
            old_name='comment',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='pokersessioncomment',
            name='poker_session',
        ),
        migrations.AlterField(
            model_name='pokersessionupdate',
            name='buy_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pokersessionupdate',
            name='chip_stack',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pokersessionupdate',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokersessions.PokerSessionComment'),
        ),
    ]
