# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokersessions', '0003_auto_20171013_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokersessionupdate',
            name='comment',
        ),
    ]
