# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokersessions', '0004_remove_pokersessionupdate_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokersessioncomment',
            name='poker_session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pokersessions.PokerSession'),
        ),
        migrations.AddField(
            model_name='pokersessioncomment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
